### ISSUE TITLE
hi team support

### ISSUE THREAD

**Issue by letiennam29** [kbengine/kbengine_unity3d_demo#2]
I got the following error while running server demo:

[S_ERROR]: AssertionError: KBEngine::Entity::__py_pyMoveToPoint: args require 5
args(PyObject_ptr, float, PyObject_ptr, int32, int32), gived 6! is script[Monste
r].

**Comment by kbengine** [comment]
Hi,
Update to the latest version
kbengine and kbengine_assets_demos

**Comment by letiennam29** [comment]
tks @kbengine , i update to the latest version.
I try to run again, but error after

[ERROR]: HTML5PacketFilter::recv: frame_opcode(ê) != 130, addr=127.0.0.1:53450/0
/0/0
[ERROR]: 127.0.0.1:53450: Exception occurred: REASON_HTML5_ERROR

**Comment by kbengine** [comment]
Use html5demo to login?

**Comment by letiennam29** [comment]
I run demo success, when change using client kbengine_unity3d_demo.
tks @kbengine :)
