### ISSUE TITLE
無法編譯成WebGL專案

### ISSUE THREAD

**Issue by liangyenchen** [kbengine/kbengine_unity3d_demo#5]
如題, WebGL下是沒有Socket的

**Comment by kbengine** [comment]
Sorry， 这个demo并没有考虑web。
另一个demo才专门针对了web，https://github.com/kbengine/kbengine_cocos2d_js_demo

**Comment by liudaafang** [comment]
unity可以适应WebGL， 应该问题不大哦，看下有什么问题发来看看吧，有空我编译试试
