### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by shadowver** [kbengine/kbengine_unity3d_demo#9]
Hi,

Thanks for the work. I have encountered an issue when running the demo on Linux. Whenever I tried to login, the unity3d log showed "System.ArgumentException:Length". It appeared to be an issue in "memorystream.cs" line 137 in array.copy().  The server side runs well. Thx.

**Comment by kebiao** [comment]
What is the version of the server and client?

**Comment by shadowver** [comment]
2.0 for the server, I have tried two different demo, one from the official site and this repo, both appeared the same error

**Comment by shadowver** [comment]
I have tried the 1.9.1 server, with demo, the error states client/server version conflict.

**Comment by kebiao** [comment]
No problems with Android, Windows, and IOS.
Can you debug this problem?

**Comment by shadowver** [comment]
ya, runs on windows. I am looking into the issue. It also may caused by Linux version of Unity as it full with bugs.... are you able to reproduce the bug on linux?

**Comment by kebiao** [comment]
I haven't tested the environment now, and now I'm doing other functions and I can't test this problem.
